### ISSUE TITLE
Einheitliche Icons/Captions

### ISSUE THREAD

**Issue by schaettu** [ralphschulerSZ/WebPoint#11]
Die Icons über dem Kartenfenster sind nicht sehr selbstsprechend ich schlage folgende Bilder und folgende Captions vor (im Projektverzeichnis, Ordner Icons:
![kartenfilter](https://cloud.githubusercontent.com/assets/6048930/16990216/79d41cb8-4e97-11e6-91a1-12c270db10fe.png)   -> "Liste nach Kartenauswahl filtern"
![filter_off](https://cloud.githubusercontent.com/assets/6048930/16990255/9efe26b4-4e97-11e6-9dde-03b3e42b9928.png)  -> "Filter löschen"
![listenfilter](https://cloud.githubusercontent.com/assets/6048930/16990440/4f6063f0-4e98-11e6-86e1-cc4a2acfc10e.png)  -> "Karte auf Listenwahl zoomen"

**Comment by ralphschulerSZ** [comment]
@schaettu  Kannst Du das zweite Symbol ganz in rot machen? Ebenfalls sollten sie in der gleichen Grösse sein wie die Originalfiles von WebPoint.

**Comment by ralphschulerSZ** [comment]
test

**Comment by ralphschulerSZ** [comment]
Hier die definitiven Icons. Auch via Email versandt an Markus Lerch.

![filter1](https://cloud.githubusercontent.com/assets/11614900/18429359/29225580-78d3-11e6-89c3-1beba9f71d78.png)
![filter2_1](https://cloud.githubusercontent.com/assets/11614900/18429364/2d5c6ee2-78d3-11e6-91c0-09c6051dbd32.png)
![filter3_1](https://cloud.githubusercontent.com/assets/11614900/18429370/31566408-78d3-11e6-8d99-15270fe2e036.png)

**Comment by ralphschulerSZ** [comment]
![image_1](https://cloud.githubusercontent.com/assets/11614900/18550252/1e6a4f4e-7b53-11e6-84ff-fa753732392b.png)
