### ISSUE TITLE
Erweitern von WebPoint mit zusätzlichen Hintergrundkarten und Overlays

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#13]
Hallo @markuslerch

Wir haben im Gespräch mit künftigen WebPoint Usern bereits festgestellt, dass der Wunsch besteht, bestehende Hintergrundkarten und Overlays einblenden zu lassen. Was wir schön öfters gehört haben, ist der Wunsch nach den Liegenschaften/Grundstücke.

Ich hab mal ein wenig mit der apj.js "gepröbelt". Hier mal ein Versuch:

``` html
<html>
<head>
<title>WebPoint Overlays Testfile (main)</title>
</head>
<body>
<script src="https://map-d.geo.sz.ch/main/wsgi/api.js"></script>
<script>
window.onload = function() {

var map = new geoportal.Map({
    div: 'map1',
    zoom: 4,
    center: [691850, 207852],
    layers: ['ch.sz.swisstopo.pixelkarte_farbe.wms','ch.sz.a018.amtliche_vermessung.liegenschaften.liegenschaft','ch.sz.avg.avg_grenzen.gemeindegrenze','ch.sz.avg.avg_grenzen.gemeindenamen'],
    addLayerSwitcher: true,
    layerSwitcherExpanded: true,
    addMiniMap: true,
    miniMapExpanded: true,
    showCoords: true
    })

};
</script>
<div id='map1' style='width:1000px;height:600px;'></div>
</body>
</html>
```

Dieser Code erzeugt folgendes Map-Control:

![2016-07-21 14_44_19-webpoint overlays testfile main](https://cloud.githubusercontent.com/assets/11614900/17023051/a9a442fa-4f51-11e6-9166-e809332a5593.png)

Den oberen Teil "Grundkarte" können wir selber bewirtschaften im File:
https://github.com/camptocamp/schwyz_geoportal/blob/master/geoportal/templates/api/mapconfig.js

Der zweite Teil "Overlays" ist konfigurierbar über unsere WMS-Layernamen.

Wir haben nun vor für WebPoint ca. 5-10 vordefinierte Overlays bereitzustellen (alle öffentlich zugänglich, d.h. keine Authentifizierung nötig), sowie ein paar Hintergrundkarten. Mit den Hintergrundkarten haben wir zwar noch Probleme mit dem GMF-Framework. Siehe https://github.com/camptocamp/schwyz_geoportal/issues/303. Wir hätten aber notfalls die Möglichkeit alle Hintergrundlayer auch als Overlay darzustellen.

Meine Frage nun: **Wäre es möglich die oben genannten Funktionalitäten in WebPoint mit einzubauen?** Dies wäre ein grosser Gewinn für das Produkt.

**Comment by markuslerch** [comment]
Hallo Ralph

Ich habe es nicht im Detail angeschaut. Vorderhand mit einem grundsätzlichen Statement:

Es ist sicherlich möglich, und ein grosser Mehrwert, weitere Layer in WebPoint zur Verfügung zu stellen.

Im Moment werden die Hintergrundlayer statisch zugefügt (im WebPoint Konfigurations-Code).
Hier müsste man einen Weg definieren, damit ihr die selber erweitern und integrieren könnt.
Der "billigste" Weg wäre wohl, das Config zu erweitern. Aber mir scheint es nicht optimal.

Auch wird es vermutlich Layer geben, die ihr in Abhängigkeit der gewählten Feature Class anbieten wollt.
Mir scheint, man sollte da den Layer-Tree verwenden, der mit GMF mitkommt und eher nicht eine reine OpenLayer Schiene fahren. Muss aber nicht sein.

Warum nicht gemeinsam die Anforderungen zusammenzutragen und dann ableiten, was der "nachhaltigste" Weg ist, damit wir uns nicht zu sehr von GMF entfernen und ihr trotzdem selber "erweitern" könnt, wenn ihr wollt. Ich kann dir sonst gerne zeigen, wie es zur Zeit implementiert ist, Der WebPoint Source Code ist ja auch Teil der Auslieferung.

Ich schlage vor, dass ich mit Beat spreche, damit er das koordinieren kann, ok?

Gruess Markus

**Comment by ralphschulerSZ** [comment]
Hallo Markus

Vielen Dank für das ausführliche Statement. Da zur Zeit Kuno in den Ferien weilt (er ist ab 2. August wieder da), will ich da noch nicht zu weit vorgreifen.

Wenn wir davon ausgehen, dass wir ein paar "grundsätzliche" Layer zur Verfügung stellen wollen, muss es meines Erachtens nicht zwingend FeatureClass abhängig sein. Ich (evtl. auch Kuno) stelle mir das so vor, dass der User aus einer vordefinierten Liste (die vllt. durchaus bis zu 10 Items beinhaltet) auswählen kann, auch solche die nicht zu seiner FeatureClass "passen" sollten.

Warum nicht der Weg "Config erweitern"? Wir sind bezgl. GMF-Framework "Weltmeister" darin. ;-) Gerne wäre ich interessiert, wenn Du uns zeigen könntest wie man die Config diesbezüglich erweitert.

Ich denke es ist sicherlich am sinnvollsten wenn Beat dies mit Kuno koordiniert (eben wie gesagt, ab 2. August). Ich selber bin vom 1. August weg und erst am 22. August wieder da.

Ich werde Ende dieser Woche Kuno via WebPoint-"Summary" Email auf diesen Issue aufmerksam machen.

Besten Dank und Gruss
Ralph
