### ISSUE TITLE
Namen und ToolTip bei Geometriebearbeitung anpassen

### ISSUE THREAD

**Issue by KunoEpper** [ralphschulerSZ/WebPoint#15]
Beim Editieren der Geometrie erscheint das Fenster "Objekt ändern" mit drei Schaltflächen. Bitte die Namen und deren Tooltip wie folgt ändern:
- Speichern: Name belassen; Tooltip: Änderungen speichern"
- Löschen: Name belassen; Tooltip: "Objekt löschen"
- Annulieren: Name neu: "Abbrechen"; Tooltip: "Vorgang abbrechen"

**Comment by ralphschulerSZ** [comment]
Kann der Code diesbezüglich geändert werden?

**Comment by ralphschulerSZ** [comment]
Icon sollte die gleichen Abmessungen haben wie Original...
