### ISSUE TITLE
UUID muss selektierbar sein

### ISSUE THREAD

**Issue by KunoEpper** [ralphschulerSZ/WebPoint#16]
Im Bearbeitungsmodus eines Objektes soll die UUID selektierbar (markierbar) sein (aber nicht editierbar).

**Comment by ralphschulerSZ** [comment]
Kann Markus dies bewerkstelligen?

**Comment by ralphschulerSZ** [comment]
Ist selektierbar, wenn man im Anzeigen Modus ist. Siehe Screenshot:
![2016-08-23 16_24_46-avg_test_polygon - 42](https://cloud.githubusercontent.com/assets/11614900/17895686/2bbc909c-694e-11e6-9017-951de3fe1d11.png)
