### ISSUE TITLE
Geometrie editieren: Reduktion der Klicks

### ISSUE THREAD

**Issue by KunoEpper** [ralphschulerSZ/WebPoint#17]
Weshalb ist beim "Element bearbeiten" der Kartenteil nicht eingeblendet?

Wäre es möglich, bei "Element anzeigen" die Events für Klick auf "Geodaten bearbeiten" und "Editieren" bereits abzusetzen (bzw. zumindest den ersten Klick-Event)?
Dies würde den Benutzer ein wenig "entlasten".

**Comment by ralphschulerSZ** [comment]
Kann evtl. mit SharePoint List Erstellung mit spez. Buttons gelöst werden.

Muss mit Markus Lerch noch geklärt werden, ob es technische Hintergründe für dieses Verhalten hat. Gibt es eine einfachere Lösung?
