### ISSUE TITLE
Beim Löschen eines Sharepoint Items wird die dazugehörige Geometrie nicht mitgelöscht

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#21]
Beim Löschen eines Sharepoint Items wird die dazugehörige Geometrie nicht mitgelöscht. Dies hat dann zur Folge, dass der Geometrie-Record auf der GIS-DB verwaist ist. Dies wäre an und für sich noch nicht ein grosses Problem, da wir die Möglichkeit hätten bspw. mit einem FME-Workbench dieses verwaisten Daten regelmässig automatisiert zu löschen.

Dem User selber aber bleibt diese Möglichkeit verwehrt. D.h. er hat keine Chance, selber einen von ihm erzeugten Fehler zu korrigieren. Sehe ich das so richtig?

Beim Benutzen des Kartenauswahlfilters erscheinen dann viele Tooltips welche störend wirken können.
![2016-08-23 08_17_22-edit data - dev localhost_54351 - geoportal - webpoint t04a_testing1_polygon](https://cloud.githubusercontent.com/assets/11614900/17882053/5bc8a49a-690a-11e6-84b4-9608ef1a7bcc.png)

Gibt es hier eine der folgenden Möglichkeiten zum Umsetzen?
- Der User löscht das SharePoint-Item, gleichzeitig werden die verknüpften Geometrien auf der GIS-DB auch gelöscht (ohne Rückfrage).
- Dem User wird die Möglichkeit gegeben, eine verwaiste Geometrie selber zu löschen.
- Die verwaisten Geometrien werden vom AVG automatisiert (via FME) gelöscht, jedoch müssten dann die Tooltips nicht eingeblendet werden.

**Comment by ralphschulerSZ** [comment]
kann ohne Rückfrage gelöscht werden. User muss nicht gewarnt werden.

**Comment by ralphschulerSZ** [comment]
Email von Markus:

> Der Zentrale Ansatz erweist sich als nicht so einfach wie gedacht. 
> 
> Ich wollte mich am «onDelete» Ereignis des Standard List Controls registrieren. Dies wird aber eben vielfältig aufgerufen (z.B. auch beim Filtern / Pagen usw.) und enthält keine Informationen über die «Absicht» des Aufrufs. Daher müsste man auch hier die verschiedenen «Delete» Eintrittsstellen abdecken.  
> 
> Ein DB-Listen-Trigger Ansatz ist auch mit erheblichem Aufwand verbunden, da wir die dazu notwendige «Remote-event-listener» Technologie nicht einsetzen und einen eigens dafür benötigten Deployment Mechanismus aufbauen müssten.
> 
> Ich suche noch nach einem pragmatischen effektiven Lösungsansatz und melde mich nächste Woche.
> 
> Das Ausschalten der Tooltipps wäre grundsätzlich einfach zu bewerkstelligen.

**Comment by markuslerch** [comment]
Lieber Ralph, lieber Kuno

nach längerem Suchen und abwägen schlagen wir folgenden Lösungsweg vor:

**Das Löschen der Sachdaten soll nicht mehr über die Standardfunktionalität von SharePoint, sondern über einen WebPoint-Lösch-Button ausgelöst werden.**
Der Lösch-Button wird direkt auf dem List-Item der SharePoint Standardliste (rechts von der Check-Box) angebracht und nur eingeblendet, wenn der Benutzer entspr. Berechtigungen hat.

Vorteile:
- Bestehende Konzepte werden erweitert
- Robustes Verhalten bei Software updated

Nachteile:
- Anwender müssen geschult werden, dass Daten nur (Gis-)konsistent gelöscht werden, wenn sie den WebPoint Lösch-Button verwenden.
- Bulk-Deletes (mehrere Listeneinträge selektieren) sind in V1 nicht vorgesehen

Das Löschen der Sachdaten über die Standardfunktionalität ist nach wie vor möglich. Dessen angebrachte Verwendung liegt im Ermessen des Anwenders. Man könnte dies per Berechtigungen (auch später noch) unterbinden, wir gehen aber davon aus, dass das nicht ideal ist, da es zusätzliche administrative Schritte beim Konfigurieren einer Feature Class erfordert.

Könnt ihr mit dem Ansatz leben?

Gruess Markus

**Comment by ralphschulerSZ** [comment]
Hallo Markus

Vielen Dank für die Abklärungen. Leider habe ich Deinen Beitrag erst jetzt bemerkt, sorry! Ich denke wir werden diesen Punkt morgen im Skype-Meeting besprechen.

Gruss, Ralph

**Comment by ralphschulerSZ** [comment]
Vorschlag Benennung des Funktionskollonenfeld:

Name: "function_icons"
Anzeigename des Titels: würde ich leer lassen, da Tooltips auf jeweiligem Icon vorhanden.

Andere Vorschläge gerne willkommen!

**Comment by KunoEpper** [comment]
Leider kann die Spaltenüberschrift das GUI nicht leer sein, aber da wird uns schon was kurzes einfallen.
Wichtig ist die Vorgabe des Namens, welcher erstmalig angelegt wird und mit dem Vorschalg von Ralph bin ich enverstanden (in Einzahl):
**function_icon**

**Comment by ralphschulerSZ** [comment]
Der neue Button (unter FNC) scheint nur teilweise zu funktionieren...

Bei folgender Klasse scheint es gar nicht möglich zu sein zu löschen:
https://avgsz.sharepoint.com/sites/webpoint/Lists/Line_21781_2/AllItems.aspx (bspw. ID 1)

Bei Polygonen hat es bisher immer geklappt:
https://avgsz.sharepoint.com/sites/webpoint/Lists/Polygon_21781_4/AllItems.aspx

Bei Linien teilweise:
https://avgsz.sharepoint.com/sites/webpoint/Lists/Line_21781_2/AllItems.aspx

Markus, könntest Du das bitte nochmals anschauen?

Danke und Gruss
Ralph

**Comment by markuslerch** [comment]
Hallo Ralph
Ich konnte den Bug reproduzieren und habe den Bugfix auf eurer Umgebung eingespielt. Bitte Cache löschen.

Es wurde jeweils immer das letzte Item (inkl. Geometrie) in der Listenansicht gelöscht. Daher wohl die Wahrnehmung, dass es "manchmal" löscht und manchmal nicht.

Wir haben beim Deployment im Provisioning eine Anpassung gemacht, damit das FNC-Feld schreibgeschützt erzeugt wird, und dort niemand Daten eingeben kann.
Dies hat nun dazu geführt, dass sich JS-Selektoren anders verhalten (readonly property).
- Wir konnten dies unmittelbar nach dem Deplyment nicht testen, da das Problem mit der Projektion bestand und generell keine Geometrien mehr gelöscht werden konnten.
- Bei meinem Schnelltest nach dem Projektions-Fix ist es mir nicht aufgefallen. Ich habe wohl von unten nach oben gelöscht...

Gruess Markus

**Comment by ralphschulerSZ** [comment]
Hoi Markus

Danke für den Fix. Jetzt scheint alles wie gewünscht zu funktionieren.

Gruss, Ralph
