### ISSUE TITLE
Inkonsistenzen bei Filter-Funktionen

### ISSUE THREAD

**Issue by KunoEpper** [ralphschulerSZ/WebPoint#22]
Einzelne Anwendungsfälle mit der Filterfunktion (Kartenfilter und/oder Listenfilter) führen zu Inkonsistenzen. Eine Schritt-für-Schritt-Anleitung ist beigelegt.
[Testresultate als Anhang zu Issue.pdf](https://github.com/ralphschulerSZ/WebPoint/files/432664/Testresultate.als.Anhang.zu.Issue.pdf)

**Comment by markuslerch** [comment]
**Bug 1)** Aus Ablauf 3a: Sicherstellen, dass auch nach Betätigung von "Filter löschen" das erste selektierte Sachdaten-Item in der Karte als "highlighted" dargestellt wird.

**Bug 2)** Aus Ablauf 4: Wenn Spaltenfilter Gemeinde (Einsiedeln) und ID-Filter gesetzt sind, wird der ID-Filter bei einem «Maximale Ausdehnung anzeigen» nicht unmittelbar auf die Karte angewendet -> beide Einsiedeln-Geometrien sind sichtbar. Bei der nächsten Aktion (Selektieren des Höhronen-Items) korrigiert sich die Applikation selbständig.

**Comment by ralphschulerSZ** [comment]
Kuno: ID-Spalte immer einblenden ok.

**Comment by ralphschulerSZ** [comment]
Email von Markus:

> Nach dem löschen des Spaltenfilters (Einsiedeln) erscheinen lediglich zwei Sachdaten-Records, da neben dem Spaltenfilter Gemeinde noch der Spaltenfilter ID gesetzt ist. Der ID-Filter wird ja immer gesetzt, wenn der Kartenausschnitt Filter benutzt wird. Dies bleibt dem Anwender aber verborgen, da die ID-Spalte ausgeblendet wurde.
> 
> Allenfalls wäre es für den Endbenutzer besser verständlich, man lässt die ID-Spalte standardmässig eingeblendet.
> 
> Bei Ablauf 4) verbleibt somit folgender Bug: 
> 
> Wenn Spaltenfilter Gemeinde (Einsiedeln) und ID-Filter gesetzt sind, wird der ID-Filter bei einem «Maximale Ausdehnung anzeigen» nicht unmittelbar auf die Karte angewendet -> beide Einsiedeln-Geometrien sind sichtbar. Bei der nächsten Aktion (Selektieren des Höhronen-Items) wird das dann korrigiert.

**Comment by ralphschulerSZ** [comment]
Aussage Kuno: ID-Spalte immer einblenden ok.

**Comment by KunoEpper** [comment]
zu Bug 1): Laut Aussage von Markus kann dieser nicht gelöst werden
==> Wir müssen mit der Situation leben und daher ist der Retest ok
zu Bug 2): Durch das Einblenden der ID-Spalte hat sich die vermeintliche "Inkonsistenz" entschärft. Ein kleiner Mangel ist der Verlust der "Kartenauswahl filtern" (grau markiertes Icon). Aber auch das scheint nicht einfach zu lösen.
==> Wir müssen mit der Situation leben und daher ist der Retest ok
