### ISSUE TITLE
bei Startposition Zoomstufe immer auf 1

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#23]
Hallo Markus

Dies ist ein Punkt, den wir noch vergessen haben im letzten Skype-Meeting. Sorry!

Da Du aktuell dran bist den Code zu ändern, wäre es allenfalls möglich diesen Issue in v1 einfliessen zu lassen? **Ich hoffe, es gibt nicht allzu viel Aufwand. Ansonsten lass es mich bitte wissen.**

Gerne würden wir, wenn das MapControl aufgerufen wird, immer auf der Zoomstufe 1 starten. Der User findet sich wahrscheinlich so besser zurecht. Siehe Screenshot:

![2016-09-07 10_20_19-avg_test_polygon](https://cloud.githubusercontent.com/assets/11614900/18304871/273599f4-74e5-11e6-86a7-624b605b2aab.png)

**Comment by markuslerch** [comment]
Hallo Ralph
wir können das so anpassen.
Gruess Markus

**Comment by ralphschulerSZ** [comment]
Test OK
