### ISSUE TITLE
bei Polygon Klasse wird Symbolisierung nicht von Mapfile übernommen

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#28]
Hoi Markus

Beim Retesten von v1 habe ich festgestellt, dass die Symbolisierung bei einer Polygon Klasse nicht aus dem Mapfile übernommen wird. Es scheint, dass die Standardsymbolisierung verwendet wird:

![1](https://cloud.githubusercontent.com/assets/11614900/19040880/32e583b2-8986-11e6-876d-5377e3e229da.png)

Sollte aber so aussehen:

![2](https://cloud.githubusercontent.com/assets/11614900/19040888/3df7bf2c-8986-11e6-82aa-48fb6cadc480.png)

Siehe auch:

https://map-d.geo.sz.ch/main/wsgi/short/qMOxDU
oder
https://map-d.geo.sz.ch/rschuler/wsgi/mapserv_proxy?version=1.0&service=WMS&request=getstyles&layers=webpoint.polygon_21781

Könntest Du da bitte nochmal nachschauen?

Besten Dank und Gruss
Ralph

**Comment by markuslerch** [comment]
Hallo Ralph
Ich kann es nicht reproduzieren. Es scheint mindestens nicht immer der Fall zu sein.

![image](https://cloud.githubusercontent.com/assets/8824658/19042613/0c04db80-8963-11e6-8988-172c80da810d.png)

Kannst du es nochmals anschauen?
Gruess Markus

**Comment by ralphschulerSZ** [comment]
Ja tatsächlich. Vllt. ein Browser-Cache Problem meinerseits. Ich schaue es nochmal an. Danke und Gruss, Ralph

**Comment by ralphschulerSZ** [comment]
Komme aber heute nicht mehr dazu. Werde mich morgen melden. (Bei uns ist Feierabendzeit) ;-)

Gruss nach Uruguay.

**Comment by ralphschulerSZ** [comment]
Habe mit firefox -p ein neues Profil erstellt und hier kommt es auf Anhieb wie gewünscht:
![1](https://cloud.githubusercontent.com/assets/11614900/19064407/784b19c6-8a0d-11e6-8495-d80fc529dcb1.png)

Es scheint was mit dem lokalen Browserchache zu tun zu haben. Wir werden dies erwähnen in der internen Installationsanleitung.
