### ISSUE TITLE
Switch von map-d.geo.sz.ch nach edit.geo.sz.ch

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#31]
Hallo Markus

Wir haben alle Demos durch. Der Host edit.geo.sz.ch scheint auch bereit. Könntest Du mal, wie schon seit längerem geplant, den Switch in WebPoint veranlassen:

**alter Host: map-d.geo.sz.ch
neuer Host: edit.geo.sz.ch**

Mindestens folgende Feature-Class sollte funktionieren.
https://avgsz.sharepoint.com/sites/webpoint/Lists/Polygon_21781_4/AllItems.aspx

Ich habe die Symbolisierung verändert, damit wir sehen, ob wir auf den richtigen Host zeigen:
https://edit.geo.sz.ch/main/wsgi/short/Lk4IKd

Ich bin mir aber nicht ganz sicher, ob alles auf Anhieb klappt. Bitte nicht allzu viel Zeit verwenden, falls ein Problem auftauchen sollte.

Ich bin frühestens ab Dienstag 25.10.2016 erreichbar.

Besten Dank und Gruss
Ralph

**Comment by markuslerch** [comment]
Hallo Ralph

Ich habe die Umstellung noch nicht vorgenommen. Ich melde mich morgen bei dir.

Gruess Markus

**Comment by markuslerch** [comment]
Hallo Ralph
ich habe die Umstellung vorgenommen. Leider klappt noch nicht alles.

**Probleme gibt es grundsätzlich bei den Tiles:**
z.B. https://tile2.edit.geo.sz.ch/main/tiles/1.0.0/grundkarte/default/2013/swissgrid/2/4/11.png wird nicht gefunden

https://tile2.map-d.geo.sz.ch/main/tiles/1.0.0/grundkarte/default/2013/swissgrid/2/4/11.png
jedoch schon

**Zudem scheint der Layer webpoint.polygon_21781 nicht zu existieren.** Ist der einfach falsch eingetragen in der FeatureClass?

https://webpoint-sz.azurewebsites.net/proxies/wms/main/wsgi/mapserv_proxy?version=1.0&amp;service=WMS&amp;request=getstyles&amp;layers=webpoint.polygon_21781
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows" version="1.1.0" language="en-US" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="typename">
    ows:ExceptionTextmsWFSGetFeature(): WFS server error. TYPENAME 'webpoint.polygon_21781' doesn't exist in this server.  Please check the capabilities and reformulate your request./ows:ExceptionText
  /ows:Exception
/ows:ExceptionReport

Gruess Markus

**Comment by ralphschulerSZ** [comment]
Hoi Markus

Vielen Dank für die Arbeit.

Bezgl. WFS muss ich noch abklären. Da scheint noch was falsch zu sein bei uns.

Warum die Tiles nicht gefunden werden liegt daran, dass wir für edit.geo.sz.ch kein Wildcard-Zertifikat verwenden.

**Würde es WebPoint zulassen, dass wir statt tileXY.edit.geo.sz.ch bspw. tileXY.map.geo.sz.ch verwenden können?**

Im Hintergrund ist immer der gleich Tile-Server auf S3, unabhänig über welche Domain er angesprochen wird. Das würde für uns nur bedeuten, dass wir ein wesentlich teureres Wildcard-Zertifikat für edit.geo.sz.ch beantragen müssten. Wenn es für WebPoint "einfach" wäre tileXY.map.geo.sz.ch zu verwenden würden wir diese Lösung vorziehen. Ansonsten werden wir ein anderes Zertifikat beantragen.

Besten Dank und Gruss
Ralph

**Comment by markuslerch** [comment]
Hallo Ralph
Bez. den Tiles:
Die Konfiguration ist zur Zeit nicht darauf ausgelegt, separate Pfade für die versch. Geodatenquellen zuzulassen. Wir müssten das on V2 entsprechend erweitern.

Als Übergangslösung könnte ich die Route zu den Tiles "hart" im JavaScript definieren. Das liesse sich mit wenig Aufwand machen.
-> Kannst du mir mitteilen, ob ihr auf ein Root Cert. umsteigen wollt / könnt, oder ob ich den Workaround einarbeiten soll?

Gruess Markus

**Comment by ralphschulerSZ** [comment]
Hoi Markus

Gerne würden wir Deinen vorgeschlagenen Workaround anwenden. Wir schauen das in V2 genauer an.

Besten Dank und Gruss
Ralph

**Comment by markuslerch** [comment]
Hallo Ralph

ich habe den Pfad zu den Tiles nun auf tileXY.map.geo.sz.ch umgestellt. Die Karte wird nun angezeigt.

Gruess Markus
