### ISSUE TITLE
Listennnamen wird geändert => MapControl wird nicht mehr dargestellt

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#34]
Der Listenname wird verändert unter Einstellungen, Websiteinhalte, [Liste], Einstellungen, "Listenname, -beschreibung und -navigation" von bspw. original **A074A_Ueberwachungsgebiet** nach **A074A UGtest** 

![grafik](https://cloud.githubusercontent.com/assets/11614900/26617694/d5f4879e-45d6-11e7-8c4d-0174d73aafb5.png)

Dieselben Änderungen werde durchgeführt auf Einstellungen, Websiteinhalte, wpFeatureClasses, [FeatureClass], Bearbeiten unter Titel und FeatureClass (Geben Sie die Beschreibung ein).

![grafik](https://cloud.githubusercontent.com/assets/11614900/26617636/8773bb3a-45d6-11e7-8fb4-07ea7038e3d9.png)

Die hat dann zur Folge, dass zwar auf der Übersichtsseite https://avgsz.sharepoint.com/sites/webpoint/Lists/A074A_Ueberwachungsgebiet/AllItems.aspx das MapControl angezeigt wird, jedoch nicht auf der Anzeigen-Seite (bspw. https://avgsz.sharepoint.com/sites/webpoint/Lists/A074A_Ueberwachungsgebiet/DispForm.aspx?ID=3&Source=https%3A%2F%2Favgsz%2Esharepoint%2Ecom%2Fsites%2Fwebpoint%2FLists%2FA074A%5FUeberwachungsgebiet%2FAllItems%2Easpx&ContentTypeId=0x0100A36509A0AF960344B1592916B6D2651F)

![grafik](https://cloud.githubusercontent.com/assets/11614900/26617750/28ed3496-45d7-11e7-9560-2162b513b91b.png)

**Comment by markuslerch** [comment]
**Der Name einer FeatureClass sowie der Name der Liste wpFeatureClasses können nicht ohne weiteres verändert werden.**

Dies, da beim Erstellen einer neuen FeatureClass mit Hilfe eines Workflows MapControl, Scripts, usw. in die Standard Ansichten (View, Edit, New) geschrieben werden, die von SharePoint für den initialen Listennamen erstellt wurden. -> Die Default Standard Ansicht wird überschrieben.
Beim Umbenennen, gehen diese Änderungen verloren oder Links brechen.

Im Prinzip könnte nach dem Umbenennen der FC in wpFeatureClasses der angehängte Workflow manuell erneut gestartet werden. Dies legt eine neue FeatureClass mit dem neuen Namen an. Die "alte" FC (Liste) ist dann aber nicht mehr verwendbar und die Daten müssen trotzdem migriert werden. 

Der empfohlene Weg zum Vorgehen wäre:
1) Neues Item in wpFeatureClasses erstellen -> neue FC Liste word vom Workflow erzeugt
2) Löschen "altes" Item in wpFeatureClasses
3) Migration der Daten von "alter" FC Liste in "neue" FC Liste
4) Löschen der "alten" FC Liste 
5) Konfiguration der Berechtigungen für "neue" FC Liste

Dies gilt nur für Listen vom Typ FeatureClasse und wpFeatureClasses.
