### ISSUE TITLE
Punktesymbole werden transparent gerendert

### ISSUE THREAD

**Issue by ralphschulerSZ** [ralphschulerSZ/WebPoint#6]
Es wurde festgestellt, dass die Punkte Symbole transaparent dargestellt werden in WebPoint, obwohl dies via Mapfile nicht so definiert ist. Siehe https://avgsz.sharepoint.com/sites/webpoint/Lists/AVG_Test_Point/AllItems.aspx

![2016-07-20 09_00_17-avg_test_point](https://cloud.githubusercontent.com/assets/11614900/16977807/a454f550-4e58-11e6-9557-7ca0bf6c2890.png)

MapFile:

```
#LayerID: 978
LAYER
    NAME "webpoint.testing1_point_"

    METADATA
    # For both WFS and WMS queries:
      "gml_include_items" "fach_id"
      "gml_types" "auto"
      "gml_featureid" "id"
      "wfs_enable_request" "*"
    END

    TYPE POINT

    STATUS ON
    CONNECTIONTYPE postgis
    EXTENT 669000 193000 722000 232000
    PROCESSING "CLOSE_CONNECTION=DEFER"
    CONNECTION "${mapserver_connection}"    
    DATA "geom FROM (
    SELECT id, fach_id, geom FROM webpoint.t06a_testing1_point
    ) AS foo USING UNIQUE id USING srid=21781"
    DUMP TRUE
    PROJECTION
        "init=epsg:21781"
    END

    CLASS
        STYLE
            SYMBOL "triangle"
            COLOR 146 0 100
            SIZE 22
        END        
    END
END
```

Dieses Verhalten tritt nicht bei Linien und Polygonlayer auf. Markus Lerch ist schon mündlich informiert worden. Er teilte mit, dass er sich diesem Problem annehmen wird.

**Comment by markuslerch** [comment]
Ich habe das Problem mit der Symbolisierung angeschaut, und gehe davon aus, dass der "Merge" - Ansatz zielführend ist.

Daher wird im WebPoint Code die Symbolisierungsinformation aus dem Layer - File ausgelesen und anhand einer Style-Rule dem Default-Style von OpenLayers überlagert.

Bei der Definition des Layer-Files muss darauf geachtet werden, dass alle "relvanten" Style Information definiert sind, damit nicht die entspr. Default-Styles zum Zuge kommen.

**Konkrete Lösung für das Problem "Punktesymbole werden transparent gerendert":**
Ergänzen in Zeile 34, https://github.com/camptocamp/schwyz_geoportal/blob/master/mapserver/include/webpoint_testdaten.map.mako

CLASS 
30         NAME "test4point_few" 
31         STYLE 
32             SYMBOL "triangle" 
33             COLOR 0 0 255 
34             SIZE 38 
               **OPACITY 100**
35         END 
36     END 

Dadurch wird der Wert fillOpacity des OL Default-Styles überschrieben.
Bemerkung: **Ich konnte es nicht selber ausprobieren**... Allenfalls muss das Attribut (in Anlehnung an die Flächen) in einer weitern Style Klasse definiert werden...

Anlog kann für vergleichbare Situationen vorgegangen werden. 
...
], 

   "defaultStyle":{ 

   "fillColor":"#ee9900", 

   **"fillOpacity":0.4,** 

   "hoverFillColor":"white", 

   "hoverFillOpacity":0.8, 

   "strokeColor":"#ee9900", 

   "strokeOpacity":1, 

   "strokeWidth":1, 

   "strokeLinecap":"round", 

   "strokeDashstyle":"solid", 

   "hoverStrokeColor":"red", 

   "hoverStrokeOpacity":1, 

   "hoverStrokeWidth":0.2, 

   "pointRadius":6, 

   "hoverPointRadius":1, 

   "hoverPointUnit":"%", 

   "pointerEvents":"visiblePainted", 

   "cursor":"inherit", 

   "fontColor":"#000000", 

   "labelAlign":"cm", 

   "labelOutlineColor":"white", 

   "labelOutlineWidth":3 

}, 
...

Das Zusammenspiel von Layer-File, SLD und OL-JavaScript Styles wird in https://askmewhy.sharepoint.com/sites/pr16003/_layouts/15/WopiFrame.aspx?sourcedoc={6F653542-DA17-4894-A495-21F497CB236B}&file=WebPoint_Simbolisierung.docx&action=default
beschrieben.

**Comment by ralphschulerSZ** [comment]
Hallo Markus

Ich habe einen neuen Testlayer (webpoint.testing1_point_0748) definiert. Hier hat die Farbe, die Grösse sowie die Opazität geändert gegenüber dem original Dreieck-Symbol (webpoint.testing1_point_)
https://github.com/camptocamp/schwyz_geoportal/commit/ed24b16706ffd83731a7f901d8d4435cc502a31c

Zudem habe ich in WebPoint (https://avgsz.sharepoint.com/sites/webpoint) in der FeatureClass AVG_Test_Point den Layer und die ID verändert.

![2016-07-28 08_04_37-featureclasses - avg_test_point](https://cloud.githubusercontent.com/assets/11614900/17202525/06dc0320-549a-11e6-8819-c99156079b1f.png)

Leider bleibt es immer noch transparent...
![2016-07-28 08_06_19-avg_test_point - bearbeiten](https://cloud.githubusercontent.com/assets/11614900/17202543/32dc575e-549a-11e6-8864-eeed8d6a134f.png)

Ich bin mir nicht sicher, hast Du inzwischen am WebPoint Code was verändert und wenn ja auf welcher Instanz?

Ich habe auch nicht verstanden was du mit "In Anlehnung an die Flächen" gemeint hast. Meinst Du, weil das Dreieck Symbol eigentlich ein Fläche ist und nicht ein Punkt, dass man die Opazität woanders definieren müsste?

**Comment by ralphschulerSZ** [comment]
Habe nachgeschaut wie das "triangle" aufgebaut ist und bin fündig geworden in einem File namens "symbols.txt":

```
# spitzes Dreieck, gefüllt
SYMBOL
  NAME "triangle"
  TYPE vector
  POINTS
    0 4
    2 0
    4 4
    0 4
  END
  FILLED true
END
```

Hilft das evtl. weiter?

**Comment by markuslerch** [comment]
Gemäss der Mapserver Dokumentation müsste es möglich sein, dem Dreicksymbol eine Transparen zu geben. Bsp: http://mapserver.org/mapfile/symbology/construction.html#examples-mapserver-4
...
LAYER  # indistinct marsh + diagonal holes in yellow
  STATUS DEFAULT
  TYPE POLYGON
  FEATURE
    POINTS
      100 30
      100 50
      140 50
      140 30
      100 30
    END # Points
  END # Feature
  CLASS
    STYLE
      COLOR 0 0 255
      SYMBOL "ind_marsh_poly"
      SIZE 25
    END # STYLE
    STYLE
      SYMBOL "diag_holes"
      SIZE 30
      COLOR 250 220 0
      **OPACITY 75**
    END # STYLE
  END # CLASS
END # LAYER
...

Dabei gehe ich davon aus, dass das mit SYMBOL "triangle" auch geht, resp. das Symbol keine Rolle spielt. Wertebereich von OPACITY: [integer | alpha] -> ob da 100 sinnvoll ist, bin ich mir nicht sicher.
-> Werte 1, 75, 100 ausprobieren und schauen ob er reagiert.

**Comment by ralphschulerSZ** [comment]
Hallo Markus

Ich habe folgenden Mapfile Code ausprobiert.

```
LAYER
    NAME "webpoint.testing1_point_0919"

    METADATA
    # For both WFS and WMS queries:
      "gml_include_items" "fach_id"
      "gml_types" "auto"
      "gml_featureid" "id"
      "wfs_enable_request" "*"
    END

    TYPE POINT

    STATUS ON
    CONNECTIONTYPE postgis
    EXTENT 669000 193000 722000 232000
    PROCESSING "CLOSE_CONNECTION=DEFER"
    CONNECTION "user=www-data password=www-data dbname=geoportal host=localhost"    
    DATA "geom FROM (
    SELECT id, fach_id, geom FROM webpoint.t06a_testing1_point
    ) AS foo USING UNIQUE id USING srid=21781"
    DUMP TRUE
    PROJECTION
        "init=epsg:21781"
    END

    CLASS
        STYLE
            SYMBOL "circle"
            COLOR 0 0 0
            SIZE 10
            OPACITY 100
        END        
    END
END
```

Resultat auf WebGIS:
https://map-d.geo.sz.ch/main/wsgi/short/fiVhrc

![2016-08-24 10_36_06-webgis kanton schwyz](https://cloud.githubusercontent.com/assets/11614900/17923936/ab890588-69e6-11e6-8273-04a44a48cefd.png)

Resultat auf Webpoint:
![2016-08-24 10_37_16-punkt0919](https://cloud.githubusercontent.com/assets/11614900/17923963/d1a0a3d4-69e6-11e6-957f-7eb1e8b51d42.png)
https://avgsz.sharepoint.com/sites/webpoint/Lists/punkt0919/AllItems.aspx

Es scheint so, dass der OPACITY Wert nur von WebGIS korrekt gerendert wird, jedoch nicht von Webpoint.

Ich bin mir nicht sicher, ob Du einen Zugang zu unserem DEV WebGIS Host hast? Wenn ja, könnte ich Dir zeigen, wie man die Mapfiles editiert. Oder sollen wir das nochmals zusammen via Skype mit Elisabeth anschauen? Was meinst Du?

Besten Dank und Gruss
Ralph Schuler

**Comment by markuslerch** [comment]
Hallo Ralf
Es scheint, dass der Opacity Wert gar nicht erst als SLD ausgeliefert wird:
https://webpoint-sz.azurewebsites.net/proxies/wms/main/wsgi/mapserv_proxy?version=1.0&amp;service=WMS&amp;request=getstyles&amp;layers=webpoint.testing1_point_0919

``````
<StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd">
<NamedLayer>
<Name>webpoint.testing1_point_0919</Name>
<UserStyle>
<FeatureTypeStyle>
<Rule>
<PointSymbolizer>
<Graphic>
<Mark>
<WellKnownName>circle</WellKnownName>
<Fill>
<CssParameter name="fill">#000000</CssParameter>
</Fill>
</Mark>
<Size>10</Size>
</Graphic>
</PointSymbolizer>
</Rule>
</FeatureTypeStyle>
</UserStyle>
</NamedLayer>
</StyledLayerDescriptor>


```Daher wirkt die Zuweisung seitens WebPoint auch nicht. Schlage vor, wir besprechen einen alternativen Lösungsweg.

Gruess Markus 
``````

**Comment by markuslerch** [comment]
gemäss http://mapserver.org/de/ogc/sld.html (Table 9. PointSymbolizer) wird Opacity ab Mapserver Version 5.4 unterstützt. Welche Version verwenden wir?

**Comment by ralphschulerSZ** [comment]
Hallo Markus

Wir verwenden aktuell die Version 7.0.0

```
[08:05:21][rschuler@ip-10-42-1-66:~/geoportal]$ /usr/lib/cgi-bin/mapserv -v
MapServer version 7.0.0 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE
[08:05:38][rschuler@ip-10-42-1-66:~/geoportal]$
```

Wenn der Opacity Wert nicht als SLD ausgeliefert wird, können wir ihn auch nicht herbeizaubern. ;-) Ich vermute, es handelt sich hierbei um einen Bug in Mapserver. Ich denke daher, dass ein alternativer Lösungsweg angebracht ist (nur bei den Punkten, bei Linien und Polygonen geht es ja).

Bestünde die Möglichkeit, den Wert via WebPoint Code immer fix auf 100% Deckkraft zu stellen? Ich meine, dass das Definieren eines Transparenzwertes für einen Punkt sowieso nicht wirklich zwingend sein müsste.

**Comment by markuslerch** [comment]
Hallo Ralph
Ja, dies wäre ärgerlich aber ein gangbarer Weg.
Gruess Markus

**Comment by ralphschulerSZ** [comment]
Hallo Markus

Auch Kuno ist einverstanden mit dem fixen Deckkraft-Wert (wir schlagen aber ca. 90% vor, damit es "benutzerfreundlicher" wirkt). D.h. wir könnten es so umsetzen.

Ich habe trotzdem mal einen Issue bei C2C erstellt:
https://github.com/camptocamp/schwyz_geoportal/issues/308
