### ISSUE TITLE
Bei Klick auf Zoom Symbol "Vergrössern", wird der Skizzenentwurf gelöscht

### ISSUE THREAD

**Issue by sutertob** [ralphschulerSZ/WebPoint#7]
Wenn der User eine neue Linie oder ein neues Polygon zeichnet und mittels Symbol "Vergrössern" einen Teil detaillierter ansehen will um genauer zu arbeiten, wird das ganze bereits gezeichnete Polygon bzw. Linie gelöscht. Der User muss wieder von vorne beginnen.

**Comment by ralphschulerSZ** [comment]
Vorschlag: die beiden Icons (Vergrössern und Verkleinern) entfernen. Der User wird mit dem Mausrad scrollen/zoomen.
