### ISSUE TITLE
drei Klicks um zu zeichnen

### ISSUE THREAD

**Issue by sutertob** [ralphschulerSZ/WebPoint#8]
Warum muss der User 3 Klicks machen um eine neue Geometrie zu erfassen. Zuerst das "Geodaten bearbeiten" Symbol, dann "Editieren" Knopf um am Schluss auf die gewünschte Geometrie zu klicken. Wäre es möglich, dass mit dem Klick auf "Geodaten bearbeiten" Symbol das Editieren schon vorgewählt ist?

**Comment by ralphschulerSZ** [comment]
siehe auch Issue #18
