### ISSUE TITLE
Dokument erloschen

### ISSUE THREAD

**Issue by schaettu** [ralphschulerSZ/WebPoint#9]
Wird editmodus gestartet und imBrowser der zurück-Knopf gedrückt, erscheint diese Meldung im Kartenfenster:
![docerloschen](https://cloud.githubusercontent.com/assets/6048930/16989530/db6667e0-4e94-11e6-8b7e-4f5a2841bf8f.jpg)

**Comment by ralphschulerSZ** [comment]
@schaettu Kannst Du das genauer beschreiben, resp. mir mal zeigen?
